#!/bin/bash

repo=$1

if [[ ! $repo == *.git ]];
then 
  repo+=".git"
fi

if [[ -d "$HOME/$repo" ]]
then
    cd "$HOME/$repo"
    git --no-pager log --branches='master*' --pretty='format:%an::%s::%ar'
fi
